### ISSUE TITLE
Getting issue in deploy Scrapy project on Scrapy Cloud 

### ISSUE THREAD

**Issue by rubhanazeem** [scrapinghub/shub#237] opened 2017-03-18 20:37 UTC
I am trying to deploy scrapy app on scrapy cloud. But after deploy, Spider is not available to run. After deploy I am getting this status. 
`{"project": 169397, "version": "f79741f-master", "spiders": 0, "status": "ok"}`
On running `scrapy list`, it is showing spider.

**Comment by vshlapakov** [comment] 2017-03-20 07:20
Hi @rubhanazeem! The issue is not related with shub tool, but with Scrapy itself: there were [changes](https://github.com/scrapy/scrapy/pull/2433#issuecomment-279451719) in Scrapy 1.3.0 modifying logic of handling import errors - as a result for current scrapy:1.3 stack import errors look like warnings in the deploy log leading to successful deploy with 0 spiders.

Later the behaviour was fixed with [the PR](https://github.com/scrapy/scrapy/pull/2632) in Scrapy 1.3.3. We plan to upgrade scrapy for scrapy:1.3 stack in a few days, after it the issue will disappear.

**Comment by redapple** [comment] 2017-03-27 11:08
@rubhanazeem , 1.3 stack has been updated last week. Can you try deploying again?

**Comment by rubhanazeem** [comment] 2017-03-27 12:50
@redapple my issue was resolved earlier by including requirements file.

**Closed** 2017-03-27 13:34 UTC
