### ISSUE TITLE
`deploy-egg` failed with some packages

### ISSUE THREAD

**Issue by starrify** [scrapinghub/shub#181] opened 2016-04-25 16:36 UTC
Reproduction of the issue:

```
pengyu@dev2:~$ shub deploy-egg --from-pypi pyproj
```

Stacktrace:

```
Traceback (most recent call last):
  File "/home/pengyu/bin/shub", line 11, in <module>
    sys.exit(cli())
  File "/home/pengyu/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/pengyu/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/pengyu/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pengyu/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pengyu/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/deploy_egg.py", line 20, in cli
    main(project_id, from_url, git_branch, from_pypi)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/deploy_egg.py", line 29, in main
    utils.build_and_deploy_eggs(project_id, apikey)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/utils.py", line 107, in build_and_deploy_eggs
    build_and_deploy_egg(project_id, apikey)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/utils.py", line 134, in build_and_deploy_egg
    _deploy_dependency_egg(apikey, project_id)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/utils.py", line 140, in _deploy_dependency_egg
    egg_name, egg_path = _get_egg_info(name)
  File "/home/pengyu/local/lib/python2.7/site-packages/shub/utils.py", line 177, in _get_egg_info
    egg_path = glob(egg_path_glob)[0]
IndexError: list index out of range
```

Additional info:
1. The same issue happens on my local laptop and on dev.scrapinghub.com
2. As a temporary workaround, I just downloaded the source code of `pyproj`, builded it locally, and deployed the .egg file to Scrapy Cloud. This way it worked well.

**Comment by jdemaeyer** [comment] 2016-04-27 12:43
Thanks for the report @starrify 

The problem is that `pyproj` has a weird `setup.py`. When running `python setup.py --name` it doesn't spit out the package name (even though `python setup.py --help` still reports that it would), but a bunch of build information.

**Comment by jdemaeyer** [comment] 2016-04-27 13:13
Ah, it does spit out the package name, but not separated by a newline from the debug information. Created https://github.com/jswhit/pyproj/pull/75

However, since we cannot possibly control the `setup.py` of every package out there, it might be viable to add a "name recovery mechanism" to `shub`.

**Comment by vshlapakov** [comment] 2018-05-24 14:28
`deploy-egg` is deprecated for a long time now, and a server-side endpoint responsible for it is disabled more than a year ago, I think we can close the issue.

**Closed by vshlapakov** 2018-05-24 14:28 UTC
