### ISSUE TITLE
shub deploy - ImportError: No module named js2xml 

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapinghub/shub#210] opened 2016-09-19 14:20 UTC
not able to shub deploy 

```
ImportError: No module named js2xml
Process terminated with exit code 1, signal None, status=0x0100
{"message": "List exit code: 193", "details": null, "error": "build_error"}

{"status": "error", "message": "Internal build error"}
Error: Deploy failed: {"status": "error", "message": "Internal build error"}
```

i can confirm that shub deploy-reqs was successful and js2xml egg was successfully deployed

```
Downloading/unpacking js2xml==0.1.2 
Downloading js2xml-0.1.2.tar.gz
Saved ./js2xml-0.1.2.tar.gz
Running setup.py (path:/home/../build/js2xml/setup.py) egg_info for package js2xml

Building egg in: /tmp/.../eggs/js2xml-0.1.2
Deploying dependency js2xml 0.1.2 to Scrapy Cloud project 
{"status": "ok", "egg": {"name": "js2xml", "version": "0.1.2"}}
```

**Comment by jdemaeyer** [comment] 2016-09-19 21:49
Closing this, Tomas confirmed that the issue is resolved for the user

**Closed by jdemaeyer** 2016-09-19 21:49 UTC

**Comment by DharmeshPandav** [comment] 2016-09-20 05:20
@krotkiewicz yes it had work. thanks !
