### ISSUE TITLE
Tests fail if you have a ~/.scrapy.cfg or a ~/.scrapinghub.yml

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/shub#193] opened 2016-07-07 16:43 UTC
Currently the login test suite fail if you have something configured in your ~/.scrapy.cfg or ~/.scrapinghub.yml

Tests depending on the environment are not guaranteed to be repeatable, these tests should be changed to run in a more isolated way.
If that's not possible, perhaps they should be marked to run only in the Travis build, checking if a Travis environment variable is present.

**Comment by jdemaeyer** [comment] 2016-08-16 15:24
Thanks Elias, I couldn't reproduce it with just a `~.scrapinghub.yml` but the `~/.scrapy.cfg` was indeed not properly isolated. Fixed in a9d7a49

**Closed by jdemaeyer** 2016-08-16 15:24 UTC

**Comment by eliasdorneles** [comment] 2016-08-16 16:03
Cool, thanks!
